version: '3.8'

services:
  processing:
    build: .
    container_name: pypcon
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ./sketches:/home

